# データサイエンス 第1回
## Pythonクイックスタート

## 1.基本文法

### ライブラリのインポート
初めに以下のスクリプトをセルにコピーした後、実行しライブラリをインポートする
慣れるまでは「おまじない」だと思っていてよい

In [3]:
# 必要に応じて次の行のコメントアウトを解除し，ライブラリをインストールしてください
!pip install geopandas matplotlib numpy pandas pyserial requests japanize-matplotlib scikit-learn setuptools

zsh:1: /Users/oosugakaito/program/2025/datescience/venv/bin/pip: bad interpreter: /Users/oosugakaito/venv/bin/python3: no such file or directory

[notice] A new release of pip is available: 25.0.1 -> 25.2
[notice] To update, run: python3.12 -m pip install --upgrade pip


In [4]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import japanize_matplotlib
%matplotlib inline

ModuleNotFoundError: No module named 'numpy'

### 表示

- `print()`関数を使うと、文字列や数値を表示できる
- 文字列はシングルクォート (`' '`) またはダブルクォート (`" "`) で囲む（どちらを使っても良い）
- 「`#`」以降はコメントとなり、プログラムとして実行されない

In [ ]:
# 文字列の表示
print("Hello")

# ダブルクォーテーション""でもシングルクォーテーション''でも良い
print('World')

# 数値も同様に表示させることができる
print(123)

# 文字列は変数に代入することもできる
s = "Hello"
print(s)

Hello
World
123
Hello


- 複数の文字列や数値を`,`で区切って入力するとスペースで区切られて表示される

In [ ]:
print("No.", 123)

No. 123


- 文字列は`+`演算子を使って結合できる
- 数値を`str()`に代入することで、文字列として扱うことができる
- 文字列の先頭に`f`を付け、変数や数式を`{}`で囲めば文字列に埋め込むことができる

In [ ]:
name = "太郎"
age = 25

# 通常のprint関数の使い方
print("名前は " + name + " で、年齢は " + str(age) + " 歳です。")

# f文字列を使ったprint関数の使い方
print(f"名前は {name} で、年齢は {age} 歳です。")

名前は 太郎 で、年齢は 25 歳です。
名前は 太郎 で、年齢は 25 歳です。


### 各種演算

- 四則演算は`+`, `-`, `*`, `/`の記号を用いて計算する
- `%`で剰余（割り算の余り）、`**`でべき乗を計算できる

In [ ]:
a = 5
b = 2
print("a =", a)
print("b =", b)
print("a + b =", a+b)   # 和の計算
print("a - b =", a-b)   # 差の計算
print("a * b =", a*b)   # 積の計算
print("a / b =", a/b)   # 商の計算
print("a % b =", a%b)   # 剰余の計算
print("a ** b =", a**b) # べき乗の計算

a = 5
b = 2
a + b = 7
a - b = 3
a * b = 10
a / b = 2.5
a % b = 1
a ** b = 25


<span style="font-size: 20px; color: #F08000;">[問題1-1] 四則演算の練習</span>

- $2$を$10$個かけてできる数$2\times2\times2\times2\times2\times2\times2\times2\times2\times2$を$17$で割った余りは___です（灘中学校入試問題, 2022）

- また、$2$を$2022$個かけてできる数$2\times2\cdots\times2$を$17$で割った余りは___です（灘中学校入試問題, 2022）

In [ ]:
##############################
# 問題1-1のコードを記入
a=2
b=10
c=17
d=2022
print(a**b%c)
print(a**d%c)
##############################

4
13


<span style="font-size: 20px; color: #F08000;">[問題1-2] 四則演算の練習</span>

- $7777777777\times7777777777$を計算すると$20$桁の整数になります。この20桁の整数の上10桁、下10桁をとりだして、れぞれ10桁の整数A、Bをつくります。このとき、A+B=___です。
（灘中学校入試問題, 2016）

In [ ]:
##############################
# 問題1-2のコードを記入
a=7777777777**2
b=int(a*(10**-10))
c=b*10**10
d=a-c
e=b+d
print(a)
print(b)
print(c)
print(d)
print("A+B=",e)
##############################

60493827148395061729
6049382714
60493827140000000000
8395061729
A+B= 14444444443


### リスト

- リストとは
  - 複数のデータ（文字列や数値）を一つにまとめて扱うためのデータ構造
- 複数の数値をカンマで区切り、両端を`[]`で囲むとリストになる

In [ ]:
arr = [100, 200, 300]

print('arr:', arr)

arr: [100, 200, 300]


- リストの`x`番目の要素へのアクセスするには`リスト[x-1]`のようにインデックスを指定する

In [ ]:
arr = [100, 200, 300]

print('arrの0番目の要素は', arr[0])
print('arrの1番目の要素は', arr[1])
print('arrの2番目の要素は', arr[2])

arrの0番目の要素は 100
arrの1番目の要素は 200
arrの2番目の要素は 300


- リストの長さを求めるには `len()` を用いる

In [ ]:
arr = [100, 200, 300]

print('arrの長さは', len(arr))

arrの長さは 4


- `リスト[m:n]`とすると、`m`番目から`n-1`番目の要素からなるリストになる
  - `リスト[:n]`とすると、リストの先頭から`n-1`番目の要素からなるリストになる
  - `リスト[m:]`とすると、リストの`m`番目から最後尾までの要素からなるリストになる

In [ ]:
arr = [0, 1, 2, 3, 4, 5, 6, 7, 8, 9]

print('arrの長さ:', len(arr))
print('arr[3:7]', arr[3:7])
print('arr[:7]', arr[:7])
print('arr[3:]', arr[3:])

arrの長さ: 10
arr[3:7] [3, 4, 5, 6]
arr[:7] [0, 1, 2, 3, 4, 5, 6]
arr[3:] [3, 4, 5, 6, 7, 8, 9]


### 辞書

- 辞書とは
  - `キー`(key)と`値`(value)のペア（key-value）を保持するデータ型
  - `キー` で検索して `値` を取得する


1. `キー` と`値` のペアを持つ辞書の作成
   - `キー`は（基本的に）文字列，`値`は任意の型
   - `キー`と`値`をコロン`:`で区切る

In [ ]:
my_dict = {'name': 'Alice', 'age': 25, 'job': 'Engineer'}

2. 辞書の利用
   - `辞書名['キー']` とすると対応した `値` を取り出すことができる

In [ ]:
print('name:', my_dict['name'])
print('age:', my_dict['age'])
print('job:', my_dict['job'])

name: Alice
age: 25
job: Engineer


### 条件分岐　if, if-else

- 条件分岐とは
  - プログラムの実行において、特定の条件に基づいて異なる処理を実行する仕組み
1. `if`の後にスペースを入れ、条件式を書く
2. 条件式の後にはコロン`:`をつけ、次の行に真のときに実行させたい処理を書く
3. 同様に偽のときに実行させたい処理を`else:`の次の行に書く
4. 真のときおよび偽のときに実行させる処理の前にはインデント（スペース4つ）を入れる

In [ ]:
a = 5
b = 5

# if の後にスペースを入れ、条件式を書く
if a==b:                    # 条件式の後にはコロン:をつける
    print("aとbの値は等しい")  # 条件が真のときに実行させたい文
else:
    print("aとbの値は異なる")  # 条件が偽のときに実行させたい文

aとbの値は等しい


### 条件分岐　if-elif-else
- `elif`を用いるで、複数の条件分岐を続けて書くことができる

In [ ]:
a = 5
b = 3

if a==b:
    print("aとbの値は等しい")
elif a > b:
    print("aの値はbの値よりも大きい")
else:
    print("aの値はbの値よりも小さい")

aの値はbの値よりも大きい


### 条件分岐　比較演算子

| 比較演算子 | 意味                 | 例                   |
|------------|----------------------|----------------------|
| `==`       | 等しい               | `x == y`             |
| `!=`       | 等しくない           | `x != y`             |
| `>`        | より大きい           | `x > y`              |
| `<`        | より小さい           | `x < y`              |
| `>=`       | 以上                 | `x >= y`             |
| `<=`       | 以下                 | `x <= y`             |

### 繰り返し　while
```py
while 条件式:
    ループ内の処理
```
- 指定した条件が真（`True`）である限り、繰り返し処理を行う
- `if`文と同様に繰り返したい処理の前にインデント（スペース4つ）を入れる

In [ ]:
# 1から5までの数字を出力する
i = 1
while i <= 5:
    print(i)
    i += 1  # iを1ずつ増やす

1
2
3
4
5


### 繰り返し　for

```py
for 変数 in 反復可能オブジェクト:
    ループ内の処理
```
</div>
</div>

- 同じ処理を`n`回繰り返す
- `if`文と同様に繰り返したい処理の前にインデント（スペース4つ）を入れる

In [ ]:
for i in range(5):
    print("Hello") # 繰り返したい処理

Hello
Hello
Hello
Hello
Hello


- 反復可能オブジェクトとして`range()`関数を利用すると数列を生成できる
- `for i in range(n)`は`0`から`n-1`までの`n`個の整数を生成し、変数`i`に代入する

In [ ]:
# iには0以上、5未満の整数が代入される
for i in range(5):
    print(i)

0
1
2
3
4


- `for i in range(a, b)`と書くと、`a`以上`b`未満の整数を生成し、変数`i`に代入する

In [ ]:
for i in range(2, 5):
    a = i
    print('a:', a)

a: 2
a: 3
a: 4


- 反復可能オブジェクトとしてリストを利用すると各要素の値を取り出せる

In [ ]:
# リストの要素を順に出力する
fruits = ['apple', 'banana', 'orange']
for fruit in fruits:
    print(fruit)

- `for`文の中にさらに`for`文を書けば2重ループができる

In [ ]:
# 2重ループの例
for i in range(1, 4):
    for j in range(1, 3):
        print(f"i={i}, j={j}, i*j={i*j}")

i=1, j=1, i*j=1
i=1, j=2, i*j=2
i=2, j=1, i*j=2
i=2, j=2, i*j=4
i=3, j=1, i*j=3
i=3, j=2, i*j=6


<span style="font-size: 20px; color: #F08000;">[問題2] 条件分岐と繰り返し</span>

- $1$から$2017$までの整数のうち、$3$でも$4$でも割り切れないもをの考えます。そのうち、$2$の倍数と$5$の倍数はそれぞれ何個ありますか。（開成中学校入試問題, 2017）

<details>
<summary>ヒント</summary>

```py
ans_2 = 0
ans_5 = 0
for i in range(???, ???):
    if i%3!=0 and i%4!=0:
        if ???:
            ans_2 += 1
        if ???:
            ans_5 += 1

print(f"2の倍数:{ans_2}個, 5の倍数:{ans_5}個")
```
</details>

In [ ]:
##############################
# 問題2のコードを記入
ans_1=0
ans_2=0
for i in range(1,2018):
    if i%3!=0 and i%4!=0:
        if i%2==0:
            ans_1 +=1
        if i%5==0:
            ans_2 +=1

print(f"２の倍数：{ans_1}個，５の倍数：{ans_2}個")    

##############################

２の倍数：336個，５の倍数：202個


# 関数

```py
def 関数名(引数1, 引数2, ...):
    処理
    return 戻り値
```
- 関数は特定のタスクを実行するための処理のブロックを定義する方法
- 処理のブロックの前には`if`文などと同様にインデント（スペース4つ）を入れる
- `return`の後にスペースを1つ空けて戻り値を書く

In [ ]:
def func_add(x, y):
    result = x + y
    return result

a = 20; b = 30
c = func_add(a, b)
print("関数の戻り値は", c)

関数の戻り値は 50


## NumPy ライブラリの利用

### NumPy：数値計算を効率的に行うための機能を提供

- NumPyを用いた配列

In [ ]:
# numpy をnpという名前で読み込む
import numpy as np

# numpy配列の生成
x = np.array([1, 2, 3])
y = np.array([4, 5, 6])

# numpy配列の表示
print("x:", x)
print("y:", y)

x: [1 2 3]
y: [4 5 6]


### NumPy 配列要素の演算

In [ ]:
# numpy配列を作成する
x = np.array([1, 2, 3])
y = np.array([4, 5, 6])

print("x:", x)
print("y:", y)

# 配列の全ての要素に3を足す
print("x+3:", x+3)
# 配列の各要素同士の和
print("x+y:", x+y)

# 配列の全ての要素に3をかける
print("x*3:", x*3)
# 配列の各要素同士の積
print("x*y:", x*y)

# 全要素の和
print("sum:", np.sum(x))
# 全要素の平均
print("mean:", np.mean(x))

x: [1 2 3]
y: [4 5 6]
x+3: [4 5 6]
x+y: [5 7 9]
x*3: [3 6 9]
x*y: [ 4 10 18]
sum: 6
mean: 2.0


### リスト vs NumPy配列

リスト

In [ ]:
# リストでは配列の要素同士の四則演算のためにそれぞれの要素にアクセスが必要

x = [1, 2, 3]
y = [4, 5, 6]

a = x+y
b = [x[0]+y[0], x[1]+y[1], x[2]+y[2]]
print("x:", x)
print("y:", y)
print("x+y:", a)
print("[x[0]+y[0], x[1]+y[1], x[2]+y[2]]:", b)

x: [1, 2, 3]
y: [4, 5, 6]
x+y: [1, 2, 3, 4, 5, 6]
[x[0]+y[0], x[1]+y[1], x[2]+y[2]]: [5, 7, 9]


NumPy配列

In [ ]:
# numpy配列では要素同士の四則演算を容易に実現可能
x = np.array([1, 2, 3])
y = np.array([4, 5, 6])

print("x:", x)
print("y:", y)
print("x+y:", x+y)

x: [1 2 3]
y: [4 5 6]
x+y: [5 7 9]


### NumPy 数学関数の利用
平方根の計算　`np.sqrt`

In [ ]:
# 配列の作成
arr = np.array([1, 4, 9, 16, 25])

# 平方根を計算
sqrt_arr = np.sqrt(arr)

print(sqrt_arr)

[1. 2. 3. 4. 5.]


正弦関数の利用　`np.sin`

In [ ]:
# 配列の作成
angles = np.array([0, np.pi/8, np.pi/4, 3*np.pi/8, np.pi/2])

# 正弦関数を計算
sin_values = np.sin(angles)

print(sin_values)

[0.         0.38268343 0.70710678 0.92387953 1.        ]


## pandas ライブラリの利用

### pandas：データ操作および解析ライブラリ

In [ ]:
# pandasをpdという名前でインポート
import pandas as pd

# データフレームを作成
data = {'id':     [1, 2, 3],
        'apple':  [110, 90, 100],
        'orange': [120, 110, 120]}
df = pd.DataFrame(data)

# データフレームの表示
print(df)

   id  apple  orange
0   1    110     120
1   2     90     110
2   3    100     120


CSVファイルとして保存

In [ ]:
# CSVファイルに保存
df.to_csv('fruits.csv', index=False)

### pandas CSVデータの活用

- `read_csv()`関数を用い、CSVデータをpandasのデータフレームとして読み込む
- pandasのデータフレームを`.values`メソッドを用いてNumPy配列に変換できる
<div class="left-right">
<div class="left">
CSVデータの読み込み

In [ ]:
# CSVファイルの読み込み
new_df = pd.read_csv('fruits.csv')

# 読み込まれたデータフレームの表示
print(new_df)

   id  apple  orange
0   1    110     120
1   2     90     110
2   3    100     120


PandasのデータフレームをNumPyの配列に変換

In [ ]:
# pandasのデータフレームをNumPyの配列に変換
array = new_df.values
print(array)

[[  1 110 120]
 [  2  90 110]
 [  3 100 120]]


<span style="font-size: 20px; color: #F08000;">[問題3] ライブラリ活用の練習</span>

-  `fruits.csv` は、あるリンゴ（`apple`）とオレンジ（`orange`）の品種（`id`）ごとの単価（円）についてまとめたものである。
- リンゴとオレンジの品種ごとの購入数量（個）が `order1.csv`〜`order3.csv`，としてmanabaにアップロードされている．
- 購入数量が `order1.csv`，`order2.csv`，`order3.csv` の時の購入金額（円）を求めるプログラムを記述せよ。

In [ ]:
##############################
# 問題3のコードを記入
df1=pd.read_csv('order1.csv')
df2=pd.read_csv('order2.csv')
df3=pd.read_csv('order3.csv')
print(df1)
print(df2)
print(df3)

##############################

   id  apple  orange
0   1     30      50
1   2     20      60
2   3     40      70
   id  apple  orange
0   1    370     520
1   2    120     670
2   3    240     270
   id  apple  orange
0   2   1370    5120
1   3   1220    1670
2   1   2740    2270
